[package]
name = "nrf52demo"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
fuel_monitor = { version = "0.1.0", path = "../fuel_monitor" }
